<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="VJ-ThinkVersion" failures="1" tests="5" name="LoginModuleTcs" time="16.959" errors="0" timestamp="2022-10-07T08:13:22 IST">
  <testcase classname="executiontest12.LoginModule12Test" name="ForgetPwdTc" time="1.291"/>
  <testcase classname="executiontest12.LoginModule12Test" name="NegativeLoginTc" time="0.661">
    <failure type="java.lang.AssertionError" message="expected [Login incorrect. Please try ] but found [Login incorrect. Please try again]">
      <![CDATA[java.lang.AssertionError: expected [Login incorrect. Please try ] but found [Login incorrect. Please try again]
at executiontest12.LoginModule12Test.NegativeLoginTc(LoginModule12Test.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- NegativeLoginTc -->
  <testcase classname="executiontest12.RegistrationModule12Test" name="FieldValidation" time="2.147"/>
  <testcase classname="executiontest12.RegistrationModule12Test" name="FullnameValid" time="2.138"/>
  <testcase classname="executiontest12.RegistrationModule12Test" name="LoginNameValid" time="2.382"/>
</testsuite> <!-- LoginModuleTcs -->
